### ISSUE TITLE
Error in external monitor SplatNet3Monitor

### ISSUE THREAD

**Issue by MCJlol** [samuelthomas2774/nxapi#45] opened 2022-12-19 05:12 UTC
<img width="416" alt="Screenshot_20221218_111112" src="https://user-images.githubusercontent.com/91104933/208352446-1cfee8eb-51c2-46c6-b6ca-ffc53eab2219.png">

**Comment by MCJlol** [comment] 2022-12-19 05:13
If I keep on pressing "Retry" it comes up again (this is enhanced Discord Rich Presence)

**Comment by samuelthomas2774** [comment] 2022-12-20 15:03
Duplicate of #39.

Fixed in [v1.6.0](https://github.com/samuelthomas2774/nxapi/releases/tag/v1.6.0).

**Closed by samuelthomas2774** 2022-12-20 15:03 UTC
Labels: bug, duplicate, feature/discord, web service/SplatNet 3
